name: Renew Certbot

on:
  schedule:
      # 每两个月重新申请一次证书
      - cron: "* * */2 * *"
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: ssh renew
        run: |
          ssh -i ~/.ssh/id_rsa root@www.hufeifei.cn 'cd /certbot-nginx-docker; \
          echo 'y' | sh init-certbot.sh'
